### ISSUE TITLE
Feature: Users can register for an account

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can register for an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be greeted with a login in screen where they can input their credentials to sign into web application.

If user does not have an account they can click on the link to "register now."

User will get a success message upon registration, where they can return to login in screen upon clicking the link provided. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 5 02 42 PM](https://user-images.githubusercontent.com/99229316/171069643-1f9c1bf8-566b-4513-9c0f-a162da6b5053.png)

![Screen Shot 2022-05-30 at 5 03 47 PM](https://user-images.githubusercontent.com/99229316/171069673-729c3fc8-2ae9-4b3e-b1ea-ddd1a26734cd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a post request to create account
- [x] add get all users to index.js
- [x] add get by userId to index
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to be sign in page

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
