### ISSUE TITLE
Feature: User can view-their-account-page

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/final-project#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

users will be brought to my account page upon signing in
users can click link to create their pet profile
user can click link to create their sitter profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="254" alt="Screen Shot 2022-06-09 at 3 29 36 PM" src="https://user-images.githubusercontent.com/99229316/172956012-b2acb21f-ab53-4792-90db-1eefe684853e.png">
<img width="747" alt="Screen Shot 2022-06-09 at 3 30 08 PM" src="https://user-images.githubusercontent.com/99229316/172956020-1baa698f-cebc-4700-8447-49983589e286.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to to get sitter profile
- [x]  Update `data.sql` to to get pet profiles

### ☁️ Server

- [x] Update `server/index.js` to use tokens to upload sitters profiles to users accounts
- [x] - [ ] Update `server/index.js` to use tokens to upload pet profiles to users accounts
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to be the account page
- [x] update nav bar to have a link to access 'My Account'

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
