### ISSUE TITLE
Feature: User Can create a Pet Profile

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature 2: User Can create a Pet Profiles

Create a pet profile with data that will be stored in database

users can view pet profiles they have already created on My Account page or Create a new profile for a pet of theirs

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to create pet profiles for their pets that can be accessed via My Account or through their profiles

On My account, users can see profiles they have already created, or click 'Create a Pet Profile' to be brought to profile creation

Users will fill out the pet profile form, which will be sent to the database upon creation, and then will show a success message upon creation. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 5 15 07 PM](https://user-images.githubusercontent.com/99229316/171070261-0558a535-3250-4c88-9119-0c4ee5f45740.png)

![Screen Shot 2022-05-30 at 5 14 33 PM](https://user-images.githubusercontent.com/99229316/171070299-613ec65f-abcb-4bba-874e-e998f6ecfbe0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have more dummy data for pets
- [x] Update `data.sql` to be able to add to pet table

### ☁️ Server

- [x] Update `server/index.js` to create a POST request to add to pet table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component that is a Pet Form
- [x] make sure pet form resets on submit
- [x] style form properly
- [x] make sure table is sending right data to pgweb

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
