### ISSUE TITLE
Feature: user can create a pet sitter profile

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature 3: User Can create a Sitter Profile

User will provide additional information about themselves

data will be stored in data base

User can go back to my account on success message

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On My Account, users can click on create a sitter profile. 

user will then be brought to profile creation

information will then be sent to database

user will get success message where they can be go back My Account page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 5 19 08 PM](https://user-images.githubusercontent.com/99229316/171070534-596ce569-d107-4251-9856-ad9f8c59733e.png)
![Screen Shot 2022-05-30 at 5 19 19 PM](https://user-images.githubusercontent.com/99229316/171070540-789dfcfd-5693-4ca7-b513-d8c392682866.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to reflect the correct information with profile creation
- [x] Update `data.sql` to have a few more examples of dummy data

### ☁️ Server

- [x] Update `server/index.js` to POST new profiles to "users" / "sitterProfile"
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to be their "My Account" page where they can create new profiles
- [x] Update component to act as a form for profile creation

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
