### ISSUE TITLE
Feature: User can view a list of profiles

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature 4: User Can create view list of sitters near them

When User clicks home button they will be brought to list of pet sitters near them

if user clicks on AVI of sitter they will be brought to their profile, that contains more information (feature 4)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on Home button on Nav Bar , user will be brought to a list displaying list of profiles

Users list will display sitter's name, sitter's tagline, sitter's location, and price. 

Users can click drop down menu too

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 5 24 19 PM](https://user-images.githubusercontent.com/99229316/171070883-75962d64-1ffc-49c6-9008-65f04e00d524.png)
![Screen Shot 2022-05-30 at 5 24 27 PM](https://user-images.githubusercontent.com/99229316/171070885-9cfcefbf-706e-4678-9b90-4879dc5637e5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to to have dummy data of 2 users, 2 sitter profiles, and 2 pet profiles
- [x] Update `data.sql` to have PurrfectSitters db

### ☁️ Server

- [x] “Update server/index.js to handle GET requests for all profiles at /api/users
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to page to have list of profiles
- [x] Create Navbar with icons
- [x] make sure there are proper headings on each section
- [x] create cards for each user
- [x] make sure the data from the db is rendered correctly on list of profiles

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
