### ISSUE TITLE
Feature: Users can see more details of individual profiles by clicking on the profile

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature 5: Users can see more details of individual profiles by clicking on the profile
 
When a user clicks the Avi of a sitter they will be brought to sitters profile

Sitters profile will have more information on the sitter, such as the services they provide, their about me, their location, etc.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on image of the sitter, they will be brought to their page which has all of their information from their profile. 

This data will be the data from when the user set up their account. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 5 31 17 PM](https://user-images.githubusercontent.com/99229316/171071289-9531f243-d3ac-4cd7-9bd8-97f0ca1de4ad.png)

![Screen Shot 2022-05-30 at 5 31 25 PM](https://user-images.githubusercontent.com/99229316/171071294-bd967975-89b3-4df8-85a4-1657b766d1a4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to contain prices for each service provided
- [x] Update `data.sql` to match schema

### ☁️ Server

- [x] Update `server/index.js` to pull all data for user based on userId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] create profile page for sitter
- [x] implement hash routing
- [x] Update component to display correct data in the correct spots
- [x] style page to work on both mobile and desktop
- [x] implement Google Static Maps API to put location of sitter on their profiles
- [x] be able to properly display service prices for each sitter

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
